=== Witerat/CafenatedSql/CafenatedSql/schemas/cafenated.xsd
<?xml version="1.1" encoding="utf-8"?>
<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="-//org.witerat/cafenated/sql" 
	xmlns:csd="-//org.witerat/cafenated/sql"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" 
	attributeFormDefault="unqualified">
	<xsd:element name="driver">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="meta">

					<xsd:complexType>
						<xsd:attribute name="name">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:minLength value="1" />
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:attribute>
						<xsd:attribute name="description" type="xsd:string" />
						<xsd:attribute name="protocol">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:minLength value="1" />
									<xsd:whiteSpace value="collapse" />
									<xsd:pattern value="jdbc\:([a-zA-Z0-9]+)\:"></xsd:pattern>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:attribute>
						<xsd:attribute name="className">
							<xsd:simpleType>
								<xsd:restriction base="xsd:string">
									<xsd:pattern
										value="([a-z_](.[a-z_][a-zA-Z0-9_]*)*\.)?[A-Z][A-Za-z0-9]*"></xsd:pattern>
								</xsd:restriction>
							</xsd:simpleType>
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>

				<xsd:element name="template-engine" type="csd:TemplateType" />


				<xsd:element name="def" maxOccurs="unbounded" minOccurs="0">
					<xsd:complexType mixed="true">
						<xsd:sequence minOccurs="0" maxOccurs="unbounded">
							<xsd:element name="use">
								<xsd:complexType>
									<xsd:attribute name="macro"></xsd:attribute>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name='id' type="ID" />
					</xsd:complexType>

				</xsd:element>

				<xsd:element name="dialect">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name='grammar' maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="noun" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name='param' type='csd:paramType'
														maxOccurs="unbounded" minOccurs="0" />
													<xsd:element name="verb" maxOccurs="unbounded">
														<xsd:complexType mixed="true">
															<xsd:sequence>
																<xsd:element name='param' type='csd:paramType'
																	maxOccurs="unbounded" minOccurs="0" />

															</xsd:sequence>
															<xsd:attribute name="name" />
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
												<xsd:attribute name="name" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
									<xsd:attribute name="name" />
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="id" type="ID"></xsd:attribute>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="connection" type="csd:ConnectionType"
					maxOccurs="unbounded" />

			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="TemplateType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">

			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="DriverType">
		<xsd:sequence>
			<xsd:element name="template">
				<xsd:complexType>
					<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
				</xsd:complexType>
			</xsd:element>

			<xsd:element name="def">
				<xsd:complexType>
					<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
				</xsd:complexType>
			</xsd:element>


			<xsd:element name="connection" maxOccurs="unbounded"
				minOccurs="1">
				<xsd:complexType id="connType">

					<xsd:sequence>

						<xsd:element name="macro" maxOccurs="unbounded">
							<xsd:complexType>
								<xsd:attribute name="name" />
							</xsd:complexType>

						</xsd:element>
						<xsd:element name="url" minOccurs="1" maxOccurs="1">
							<xsd:complexType mixed="true">
								<xsd:sequence>
									<xsd:element name="use" maxOccurs="unbounded"
										minOccurs="0">
										<xsd:complexType>
											<xsd:attribute name="def" type="xsd:string" />
										</xsd:complexType>
									</xsd:element>
								</xsd:sequence>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="method" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MacroType" mixed="true">
		<xsd:sequence maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="use" type="csd:UseType" maxOccurs="unbounded"
				minOccurs="0"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="DefType">
		<xsd:sequence>
			<xsd:element name="param">
				<xsd:complexType>
					<xsd:attribute name="name" />
					<xsd:attribute name="type" use="optional" default="object" />

				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>

		<xsd:attribute name="macro" />
	</xsd:complexType>
	<xsd:complexType name="UseType">
		<xsd:attribute name="macro">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:minLength value="1"></xsd:minLength>
					<xsd:whiteSpace value="collapse"></xsd:whiteSpace>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>


	<xsd:complexType name="ConnectionType">

		<xsd:sequence>
			<xsd:element name="dialect">
				<xsd:complexType>
					<xsd:attribute name="name" />
					<xsd:attribute name="default" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="url" type="csd:MacroType" />
			<xsd:element type="csd:MacroType" maxOccurs="unbounded"
				minOccurs="0" name="url"></xsd:element>

		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="method" type="xsd:string"></xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="DDLType">
		<xsd:sequence>
			<xsd:element name="parameter" type="csd:paramType"
				maxOccurs="unbounded" minOccurs="0">
			</xsd:element>
			<xsd:element name="sql" type="csd:MacroType"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="paramType">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="type" type="anySimpleType" use="optional"/>
		<xsd:attribute name="default" type="anySimpleType" use="optional"/>
		<xsd:attribute name="optional" type="boolean" default="false"/>
	</xsd:complexType>
</xsd:schema>

=== Witerat/CafenatedSql/CafenatedSql-Test/resource/driver1.csql.xml
<?xml version="1.0" encoding="UTF-8"?>
<csd:driver 
	xmlns="-//org.witerat/cafenated/sql"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:csd="-//org.witerat/cafenated/sql"
	xsi:schemaLocation="-//org.witerat/cafenated/sql schemas/cafenated.xsd">
	
	<meta name="H2-Database" 
		protocol="jdbc:h2:" 
		description="H2 pure java DB"
		className="org.h2.Driver"		/>
	<template-engine>velocity</template-engine>
	<def name="params">
		#foreach($key in ${params.keys})#{set($value =
		$params[$key])};${key}=$!{value}#{end}
	</def>
	<dialect id="h2">
		<grammar name="ddl-common">
			<noun name="Schema">
				<param name="schema" type='string'></param>
				<verb name="create">
					<param name="whenMissing" type="boolean"></param>
					CREATE SCHEMA #if($!whenMissing) IF NOT EXISTS#{end}
					${dialect.renderId($schema)};
				</verb>
				<verb name="drop">
					<param name="whenPresent" type="boolean"></param>
					DROP SCHEMA #if($!whenPresent) IF EXISTS#{end}
					${dialect.renderId($schema)};
				</verb>
			</noun>
			<noun name="sequence">
				<param name="sequenceName"></param>
				<verb name="drop">
					<param name="whenPresent" type="boolean"></param>
					DROP SCHEMA #if($!whenPresent) IF EXISTS#{end}
					${dialect.renderId($sequenceName)};
				</verb>
			</noun>
			<noun name="user">
				<param name="userName" type="string" />

				<verb name="create">
					<param name="whenMissing" type="boolean"></param>
					<param name="password" type="string"></param>
					<param name="salt" type="string"></param>
					<param name="hash" type="string"></param>
					CREATE USER #if($!whenMissing) IF NOT EXISTS#{end}
					${dialect.renderId($userName)}
					#if($!password)
					$dialect.renderString($password)
					#elseif SALT $salt HASH $hash#end
					#if(isAdmin) ADMIN#end
				</verb>
				<verb name='drop'>
					<param name="whenPresent" type="boolean"></param>
					DROP USER #if($!whenPresent) IF EXISTS#{end}
					$dialect.renderId(userName)
				</verb>
			</noun>
		</grammar>
	</dialect>
	<connection method="memory">
		<use-dialect name="$mode" default='h2' />
		<url>
			jdbc:h2:mem:
			<use macro="params" />
		</url>
	</connection>
	<connection method="memory-shared">
		<use-dialect name="$mode" default='h2' />
		<url>
			jdbc:h2:mem:$dbname
			<use macro="params" />
		</url>
	</connection>
	<connection method="disk">
		<use-dialect name="$mode" default='h2' />
		<url>
			jdbc:h2:file:$!{path}${dbName}
			<use macro="params" />
		</url>
	</connection>
	<connection method="zip">
		<use-dialect name="$mode" default='h2' />
		<url>
			jdbc:h2:zip:$!{path}!${dbName}
			<use macro="params" />
		</url>
	</connection>
	<connection method="secure-server">
		<use-dialect name="$mode" default='h2' />
		<url>jdbc:h2:ssl://${host}#if(port):$port#{end};user="$userName",password="$password"
			<use macro="params" />
		</url>
	</connection>
	<connection method="server">
		<use-dialect name="$mode" default='h2' />
		<url>jdbc:h2:tcp://${host}#if(port):$port#{end};user="$userName",password="$password"
		</url>
	</connection>
	<connection method="server-memory">
		<use-dialect name="$mode" default='h2' />
		<url>jdbc:h2:$host/mem:${dbname};<use macro="params" /></url>
	</connection>
</csd:driver>
